export const menuItems = [
    // SALADS
    {
        arabicName: "حمص",
        engName: "Hammous",
        price: "0.6",
        description: "A smooth and creamy chickpea dip served with olive oil.",
        category: "SALADS",
        image: "",
        productId: "1111",
    },
    {
        arabicName: "تبولة",
        engName: "Taboola",
        price: "0.6",
        description:
            "A fresh and tangy parsley-based salad with bulgur, tomatoes, and lemon juice.",
        category: "SALADS",
        image: "",
        productId: "222",
    },
    {
        arabicName: "فتوش",
        engName: "Fatoosh",
        price: "0.5",
        description:
            "A crisp and refreshing salad with mixed greens, tomatoes, cucumbers, and toasted bread.",
        category: "SALADS",
        image: "",
        productId: "333",
    },
    {
        arabicName: "متبل",
        engName: "Mutabble",
        price: "0.7",
        description: "A creamy eggplant dip with tahini and garlic.",
        category: "SALADS",
        image: "",
        productId: "444",
    },
    {
        arabicName: "سلطة خضراء",
        engName: "Green Salad",
        price: "0.5",
        description:
            "A simple and fresh green salad with lettuce, cucumbers, and tomatoes.",
        category: "SALADS",
        image: "",
        productId: "555",
    },
    {
        arabicName: "سلطة خيار",
        engName: "Cucumber Salad",
        price: "0.5",
        description:
            "A light and refreshing cucumber salad with a touch of lemon.",
        category: "SALADS",
        image: "",
        productId: "666",
    },
    {
        arabicName: "سلطة سيزر",
        engName: "Caesar Salad",
        price: "1.0",
        description:
            "A classic Caesar salad with crisp romaine, parmesan, croutons, and Caesar dressing.",
        category: "SALADS",
        image: "",
        productId: "777",
    },
    {
        arabicName: "خيار باللبن",
        engName: "Cucumber with Yoghurt",
        price: "0.8",
        description: "A creamy and cooling cucumber and yogurt salad.",
        category: "SALADS",
        image: "",
        productId: "888",
    },
    {
        arabicName: "سلطة عربية طازجة",
        engName: "Fresh Arabic Salad",
        price: "0.6",
        description:
            "A vibrant and fresh Arabic salad with a mix of vegetables and herbs.",
        category: "SALADS",
        image: "",
        productId: "999",
    },
    {
        arabicName: "رائته",
        engName: "Raita",
        price: "0.6",
        description: "A refreshing yogurt-based dip with cucumber and spices.",
        category: "SALADS",
        image: "",
        productId: "10",
    },
    {
        arabicName: "ورق عنب )٤ قطع",
        engName: "Vine Leaves (4 pcs.)",
        price: "1.2",
        description: "Stuffed vine leaves with a tangy rice filling.",
        category: "SALADS",
        image: "",
        productId: "11",
    },
    {
        arabicName: "مازة باردة مشكلة",
        engName: "Mixed Cold Mezza",
        price: "1.5",
        description: "A variety of cold mezza items, perfect for sharing.",
        category: "SALADS",
        image: "",
        productId: "12",
    },
    // SOUP
    {
        arabicName: "شوربة دجاج بالذرة",
        engName: "Chicken Corn Soup",
        price: "0.8",
        description: "A comforting chicken and corn soup.",
        category: "SOUP",
        image: "",
        productId: "13",
    },
    {
        arabicName: "شوربة كريمة الدجاج",
        engName: "Cream of Chicken Soup",
        price: "0.8",
        description: "A rich and creamy chicken soup.",
        category: "SOUP",
        image: "",
        productId: "14",
    },
    {
        arabicName: "شوربة حارة وحامضة",
        engName: "Hot & Sour Soup",
        price: "0.8",
        description: "A spicy and tangy soup with a mix of vegetables.",
        category: "SOUP",
        image: "",
        productId: "15",
    },
    {
        arabicName: "شوربة الفطر",
        engName: "Cream of Mushroom Soup",
        price: "0.8",
        description: "A rich and creamy mushroom soup.",
        category: "SOUP",
        image: "",
        productId: "16",
    },
    {
        arabicName: "شوربة ماكوالت بحرية",
        engName: "Seafood Soup",
        price: "1.0",
        description: "A flavorful soup made with a mix of fresh seafood.",
        category: "SOUP",
        image: "",
        productId: "17",
    },
    {
        arabicName: "شوربة العدس",
        engName: "Lentil Soup",
        price: "0.8",
        description: "A hearty and comforting lentil soup.",
        category: "SOUP",
        image: "",
        productId: "18",
    },

    // APPETIZERS
    {
        arabicName: "سبرينج رول دجاج (٤ قطع)",
        engName: "Chicken Spring Roll (4 pcs.)",
        price: 1.5,
        description:
            "Crispy rolls filled with seasoned chicken and vegetables, deep-fried to perfection.",
        category: "APPETIZERS",
        image: "",
        productId: "19",
    },
    {
        arabicName: "دجاج كروكيت (٤ قطع)",
        engName: "Chicken Crockett (4 pcs.)",
        price: 1.5,
        description:
            "Breaded and fried chicken patties, crispy on the outside and tender inside.",
        category: "APPETIZERS",
        image: "",
        productId: "20",
    },
    {
        arabicName: "اصابع الدجاج (6 قطع)",
        engName: "Chicken Finger (6 pcs.)",
        price: 1.8,
        description:
            "Golden-fried chicken fingers, crispy and delicious, served with a dipping sauce.",
        category: "APPETIZERS",
        image: "",
        productId: "21",
    },
    {
        arabicName: "سمبوسة بالجبن (6 قطع)",
        engName: "Cheese Samboosa (6 pcs.)",
        price: 1.2,
        description:
            "Fried pastries filled with a savory cheese mixture, perfect as an appetizer.",
        category: "APPETIZERS",
        image: "",
        productId: "22",
    },
    {
        arabicName: "سمبوسة بالخضار (6 قطع)",
        engName: "Vegetable Samboosa (6 pcs.)",
        price: 0.8,
        description:
            "Fried pastries filled with a flavorful mix of vegetables.",
        category: "APPETIZERS",
        image: "",
        productId: "23",
    },
    {
        arabicName: "روبيان مقلي (٨ قطع)",
        engName: "Fried Prawns (8 pcs.)",
        price: 2.5,
        description:
            "Crispy and juicy fried prawns served with a tangy dipping sauce.",
        category: "APPETIZERS",
        image: "",
        productId: "24",
    },
    {
        arabicName: "روبيان تمبورا (٨ قطع)",
        engName: "Prawn Tempura (8 pcs.)",
        price: 2.5,
        description:
            "Lightly battered and fried prawns, a Japanese-style appetizer.",
        category: "APPETIZERS",
        image: "",
        productId: "25",
    },
    {
        arabicName: "السمك والبطاطس (٣ قطع)",
        engName: "Fish and Chips (3 pcs.)",
        price: 2.2,
        description:
            "Crispy fried fish fillets served with golden fries, a classic combination.",
        category: "APPETIZERS",
        image: "",
        productId: "26",
    },
    {
        arabicName: "كبة (٥ قطع)",
        engName: "Kibba (5 pcs.)",
        price: 1.2,
        description:
            "Deep-fried croquettes made of bulgur wheat, stuffed with spiced minced meat.",
        category: "APPETIZERS",
        image: "",
        productId: "27",
    },

    // GRILL
    {
        arabicName: "بيت األياود خاصة",
        engName: "Bait Al Ayawed Special",
        price: "7.5",
        description:
            "A special mixed grill platter featuring a selection of our finest grilled meats.",
        category: "GRILL",
        image: "",
        productId: "28",
    },
    {
        arabicName: "مشكل مشوي",
        engName: "Mixed Grill",
        price: "4.0",
        description:
            "Malai Boti, Sheesh Tawouk, Meat Tikka, Meat Kabab, Chicken Kabab, and Chicken Wings.",
        category: "GRILL",
        image: "",
        productId: "29",
    },
    {
        arabicName: "شيش طاووق )٤ أعواد",
        engName: "Sheesh Tawouk (4 Sticks)",
        price: "1.5",
        description:
            "Tender chicken skewers marinated and grilled to perfection.",
        category: "GRILL",
        image: "",
        productId: "30",
    },
    {
        arabicName: "دجاج تكة - بدون عظم )٤ أعواد",
        engName: "Chicken Tikka - Boneless (4 Sticks)",
        price: "1.5",
        description:
            "Juicy boneless chicken pieces marinated and grilled on skewers.",
        category: "GRILL",
        image: "",
        productId: "31",
    },
    {
        arabicName: "دجاج تكة )ربع",
        engName: "Chicken Tikka (Quarter)",
        price: "1.5",
        description:
            "A quarter portion of chicken marinated in tikka spices and grilled.",
        category: "GRILL",
        image: "",
        productId: "32",
    },
    {
        arabicName: "دجاج ماالي بوتي )٤ أعواد",
        engName: "Chicken Malai Boti (4 Sticks)",
        price: "1.6",
        description: "Creamy, flavorful chicken malai boti grilled on skewers.",
        category: "GRILL",
        image: "",
        productId: "33",
    },
    {
        arabicName: "دجاج بهاري )٤ أعواد",
        engName: "Chicken Bahari (4 Sticks)",
        price: "1.7",
        description: "Spicy Bahari chicken skewers with a rich, smoky flavor.",
        category: "GRILL",
        image: "",
        productId: "34",
    },
    {
        arabicName: "شاشليك دجاج مع أرز",
        engName: "Chicken Shashlik with Rice",
        price: "2.0",
        description: "Grilled chicken shashlik served with steamed rice.",
        category: "GRILL",
        image: "",
        productId: "35",
    },
    {
        arabicName: "كباب دجاج )٤ قطع",
        engName: "Chicken Kabab (4 pcs.)",
        price: "1.5",
        description: "Juicy chicken kababs, grilled to perfection.",
        category: "GRILL",
        image: "",
        productId: "36",
    },
    {
        arabicName: "دجاج تكة أخضر )٤ أعواد",
        engName: "Green Chicken Tikka (4 Sticks)",
        price: "1.5",
        description: "Spicy green marinated chicken grilled on skewers.",
        category: "GRILL",
        image: "",
        productId: "37",
    },
    {
        arabicName: "كباب دجاج بالجبن )٤ قطع",
        engName: "Chicken Cheese Kabab (4 pcs.)",
        price: "1.7",
        description: "Tender chicken kababs infused with cheese and grilled.",
        category: "GRILL",
        image: "",
        productId: "38",
    },
    {
        arabicName: "دجاج مشوي )كامل",
        engName: "Grilled Chicken (Full)",
        price: "3.8",
        description: "A full chicken grilled with a blend of spices.",
        category: "GRILL",
        image: "",
        productId: "39",
    },
    {
        arabicName: "دجاج مشوي )نصف",
        engName: "Grilled Chicken (Half)",
        price: "2.0",
        description: "Half a chicken grilled to perfection.",
        category: "GRILL",
        image: "",
        productId: "40",
    },
    {
        arabicName: "تكة دجاج بحريني )٤ أعواد",
        engName: "Bahraini Chicken Tikka (4 Sticks)",
        price: "1.5",
        description: "Special Bahraini-style chicken tikka grilled on skewers.",
        category: "GRILL",
        image: "",
        productId: "41",
    },
    {
        arabicName: "تكة لحم بحريني )٤ أعواد",
        engName: "Bahraini Meat Tikka (4 Sticks)",
        price: "1.8",
        description: "Flavorful Bahraini meat tikka grilled on skewers.",
        category: "GRILL",
        image: "",
        productId: "42",
    },
    {
        arabicName: "لحم بهاري )٤ أعواد",
        engName: "Beef Bahari (4 Sticks)",
        price: "1.8",
        description: "Spicy Bahari beef skewers grilled to perfection.",
        category: "GRILL",
        image: "",
        productId: "43",
    },
    {
        arabicName: "شاشليك لحم",
        engName: "Beef Shashlik with Rice",
        price: "2.4",
        description: "Grilled beef shashlik served with rice.",
        category: "GRILL",
        image: "",
        productId: "44",
    },
    {
        arabicName: "كباب لحم تركية )٤ قطع",
        engName: "Turkish Meat Kabab (4 pcs.)",
        price: "1.8",
        description:
            "Authentic Turkish-style meat kababs grilled to perfection.",
        category: "GRILL",
        image: "",
        productId: "45",
    },
    {
        arabicName: "لحم الضأن )٤ قطع",
        engName: "Lamb Chops (4 pcs.)",
        price: "6.5",
        description:
            "Tender and juicy lamb chops grilled with a blend of spices.",
        category: "GRILL",
        image: "",
        productId: "46",
    },
    {
        arabicName: "روبيان مشوي )٨ قطع",
        engName: "Grilled Prawn (8 pcs.)",
        price: "4.9",
        description: "Succulent prawns grilled to perfection.",
        category: "GRILL",
        image: "",
        productId: "47",
    },
    {
        arabicName: "حمص )6 قطع",
        engName: "Fish Tikka (6 pcs.)",
        price: "3.8",
        description: "Delicious fish tikka grilled to a perfect golden brown.",
        category: "GRILL",
        image: "",
        productId: "48",
    },
    {
        arabicName: "سمك تكة",
        engName: "Seafood of the day",
        price: "As Per Market Price",
        description: "Freshly grilled seafood, as per the day’s special.",
        category: "GRILL",
        image: "",
        productId: "49",
    },

    // CHINESE
    {
        arabicName: "لحم بقري مجفف مع أرز",
        engName: "Dry Beef Chilly with Rice",
        price: "2.4",
        description:
            "Tender pieces of dry beef stir-fried with chilies, served with steamed rice.",
        category: "CHINESE",
        image: "",
        productId: "50",
    },
    {
        arabicName: "دجاج جاف بارد مع أرز",
        engName: "Dry Chicken Chilly with Rice",
        price: "2.2",
        description:
            "Spicy stir-fried chicken with chilies, served alongside steamed rice.",
        category: "CHINESE",
        image: "",
        productId: "51",
    },
    {
        arabicName: "لحم بقري حار مع صلصة",
        engName: "Beef Chilly with Sauce",
        price: "1.8",
        description:
            "Beef cooked in a spicy chili sauce, perfect with a side of rice.",
        category: "CHINESE",
        image: "",
        productId: "52",
    },
    {
        arabicName: "دجاج بالثوم",
        engName: "Chicken Garlic",
        price: "1.6",
        description:
            "Tender chicken stir-fried with garlic, offering a robust and savory flavor.",
        category: "CHINESE",
        image: "",
        productId: "53",
    },
    {
        arabicName: "دجاج لولي بوب بالصلصة )٥ قطع",
        engName: "Chicken Lollipop with Sauce (5 pcs.)",
        price: "2.0",
        description:
            "Spicy and tangy chicken lollipops served with a flavorful sauce.",
        category: "CHINESE",
        image: "",
        productId: "54",
    },
    {
        arabicName: "دجاج منشوريان مع أرز",
        engName: "Chicken Manchurian with Rice",
        price: "2.2",
        description:
            "Classic Chinese dish with fried chicken in a tangy Manchurian sauce, served with rice.",
        category: "CHINESE",
        image: "",
        productId: "55",
    },
    {
        arabicName: "روبيان منشوريان مع أرز",
        engName: "Prawn Manchurian with Rice",
        price: "2.9",
        description:
            "Juicy prawns cooked in Manchurian sauce, served over rice.",
        category: "CHINESE",
        image: "",
        productId: "56",
    },
    {
        arabicName: "روبيان بالثوم مع أرز",
        engName: "Garlic Prawn with Rice",
        price: "3.2",
        description:
            "Stir-fried prawns with garlic, served with fragrant steamed rice.",
        category: "CHINESE",
        image: "",
        productId: "57",
    },
    {
        arabicName: "ثوم سمك مع أرز",
        engName: "Fish Garlic with Rice",
        price: "2.8",
        description:
            "Flaky fish fillets stir-fried with garlic, served with rice.",
        category: "CHINESE",
        image: "",
        productId: "58",
    },
    {
        arabicName: "أرز مقلي بالدجاج",
        engName: "Chicken Fried Rice",
        price: "1.5",
        description:
            "Classic fried rice with chunks of chicken and mixed vegetables.",
        category: "CHINESE",
        image: "",
        productId: "59",
    },
    {
        arabicName: "نباتي أرز مقلي",
        engName: "Veg. Fried Rice",
        price: "1.2",
        description: "Vegetarian fried rice with a mix of seasonal vegetables.",
        category: "CHINESE",
        image: "",
        productId: "60",
    },
    {
        arabicName: "أرز شنغهاي المقلي",
        engName: "Shanghai Fried Rice",
        price: "2.0",
        description:
            "A flavorful fried rice dish with a mix of meats and vegetables.",
        category: "CHINESE",
        image: "",
        productId: "61",
    },
    {
        arabicName: "أرز مقلي مشكل",
        engName: "Mixed Fried Rice",
        price: "2.0",
        description:
            "A delicious blend of meats and vegetables stir-fried with rice.",
        category: "CHINESE",
        image: "",
        productId: "62",
    },

    // PASTAS
    {
        arabicName: "بيني باستا بالصلصة البيضاء",
        engName: "Penne Pasta with White Sauce",
        price: "1.6",
        description: "Creamy penne pasta tossed in a rich white sauce.",
        category: "PASTAS",
        image: "",
        productId: "63",
    },
    {
        arabicName: "باستا مشروم خضار",
        engName: "Vegetable Mushroom Pasta",
        price: "1.6",
        description:
            "Pasta mixed with fresh vegetables and mushrooms, cooked in a light sauce.",
        category: "PASTAS",
        image: "",
        productId: "64",
    },
    {
        arabicName: "باستا بصلصة الكوكتيل",
        engName: "Pasta with Cocktail Sauce",
        price: "1.6",
        description: "Pasta served with a tangy and creamy cocktail sauce.",
        category: "PASTAS",
        image: "",
        productId: "65",
    },
    {
        arabicName: "نباتي شعيرية مقلية",
        engName: "Veg. Fried Noodles",
        price: "1.5",
        description: "Stir-fried noodles with a variety of fresh vegetables.",
        category: "PASTAS",
        image: "",
        productId: "66",
    },
    {
        arabicName: "شومين مختلط",
        engName: "Mixed Chowmein",
        price: "1.8",
        description: "Chowmein stir-fried with a mix of meats and vegetables.",
        category: "PASTAS",
        image: "",
        productId: "67",
    },
    {
        arabicName: "روبيان شومين",
        engName: "Prawn Chowmein",
        price: "2.5",
        description:
            "Chowmein stir-fried with succulent prawns and vegetables.",
        category: "PASTAS",
        image: "",
        productId: "68",
    },

    // CURRY ITEMS
    {
        arabicName: "لحم روغن",
        engName: "Roghan Gosht",
        price: "3.5",
        description:
            "A rich and aromatic curry made with tender pieces of meat cooked in a spiced, flavorful sauce.",
        category: "CURRY ITEMS",
        image: "",
        productId: "69",
    },
    {
        arabicName: "لحم بالتي",
        engName: "Balti Gosht",
        price: "2.5",
        description:
            "A popular curry dish made with tender meat cooked in a thick, spiced sauce, typically served in a steel wok-like dish.",
        category: "CURRY ITEMS",
        image: "",
        productId: "70",
    },
    {
        arabicName: "قورمة لحم",
        engName: "Mutton Korma",
        price: "2.5",
        description:
            "A creamy, spiced curry with tender mutton pieces, enriched with yogurt, cream, and spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "71",
    },
    {
        arabicName: "لحم أجار",
        engName: "Achar Gosht",
        price: "2.5",
        description:
            "A tangy and spicy meat curry infused with pickling spices, creating a unique and flavorful dish.",
        category: "CURRY ITEMS",
        image: "",
        productId: "72",
    },
    {
        arabicName: "لحم بالدم",
        engName: "Dum Gosht",
        price: "2.8",
        description:
            "A slow-cooked meat curry with deep, rich flavors, often cooked under pressure to retain its juices and spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "73",
    },
    {
        arabicName: "صالونة لحم",
        engName: "Mutton Kadahi",
        price: "2.5",
        description:
            "A traditional dish made with mutton cooked in a wok-like pan with tomatoes, green chilies, and spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "74",
    },
    {
        arabicName: "لحم بالسبانخ",
        engName: "Palak Gosht",
        price: "2.0",
        description:
            "A nutritious and flavorful curry made with tender meat and pureed spinach, cooked with aromatic spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "75",
    },
    {
        arabicName: "كفتة بانير",
        engName: "Kofta Paneer",
        price: "2.4",
        description:
            "Delicious paneer (cottage cheese) balls cooked in a creamy tomato-based gravy, spiced with Indian herbs.",
        category: "CURRY ITEMS",
        image: "",
        productId: "76",
    },
    {
        arabicName: "دجاج هاندي",
        engName: "Chicken Handi",
        price: "2.8",
        description:
            "A rich and creamy chicken curry cooked in a traditional clay pot, known for its depth of flavor.",
        category: "CURRY ITEMS",
        image: "",
        productId: "77",
    },
    {
        arabicName: "صالونة دجاج مع كفته",
        engName: "Chicken Kofta Curry",
        price: "2.0",
        description:
            "A flavorful curry featuring spiced chicken meatballs cooked in a rich and aromatic sauce.",
        category: "CURRY ITEMS",
        image: "",
        productId: "78",
    },
    {
        arabicName: "دجاج بالزنجبيل",
        engName: "Chicken Ginger",
        price: "2.0",
        description:
            "A spicy and aromatic curry made with tender chicken pieces cooked in a ginger-infused sauce.",
        category: "CURRY ITEMS",
        image: "",
        productId: "79",
    },
    {
        arabicName: "دجاج كورما )بدون عظم",
        engName: "Chicken Korma (Boneless)",
        price: "2.5",
        description:
            "A creamy and rich curry made with boneless chicken, cooked in a spiced yogurt sauce.",
        category: "CURRY ITEMS",
        image: "",
        productId: "80",
    },
    {
        arabicName: "قورمة دجاج )بالعظم",
        engName: "Chicken Korma (with Bone)",
        price: "1.8",
        description:
            "A traditional korma made with bone-in chicken, cooked in a creamy, spiced sauce.",
        category: "CURRY ITEMS",
        image: "",
        productId: "81",
    },
    {
        arabicName: "كراهي دجاج بالعظم",
        engName: "Chicken Kadahi with Bone",
        price: "1.8",
        description:
            "A flavorful chicken curry cooked with bone-in pieces in a wok, with tomatoes, green chilies, and spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "82",
    },
    {
        arabicName: "دجاج جالفريزي",
        engName: "Chicken Jalfrezi",
        price: "2.0",
        description:
            "A popular spicy chicken curry cooked with peppers, onions, and tomatoes, giving it a tangy and robust flavor.",
        category: "CURRY ITEMS",
        image: "",
        productId: "83",
    },
    {
        arabicName: "دجاج أوريينتل ماساال",
        engName: "Chicken Oriental Masala",
        price: "2.2",
        description:
            "A fusion curry combining the flavors of the Orient with traditional Indian spices, featuring tender chicken pieces.",
        category: "CURRY ITEMS",
        image: "",
        productId: "84",
    },
    {
        arabicName: "دجاج مكهاني",
        engName: "Chicken Makhani",
        price: "2.5",
        description:
            "A creamy, buttery chicken curry known for its rich tomato-based sauce and mild spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "85",
    },
    {
        arabicName: "قيمة كراهي",
        engName: "Keema Kadhai",
        price: "2.0",
        description:
            "A spicy minced meat curry cooked with onions, tomatoes, and green chilies in a wok-like pan.",
        category: "CURRY ITEMS",
        image: "",
        productId: "86",
    },
    {
        arabicName: "باميا مساال",
        engName: "Bhindi Masala",
        price: "1.2",
        description:
            "A delicious and spiced curry made with okra, cooked with onions, tomatoes, and Indian spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "87",
    },
    {
        arabicName: "سبانخ بالبطاطس",
        engName: "Aloo Palak",
        price: "1.0",
        description:
            "A nutritious curry made with spinach and potatoes, cooked with aromatic spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "88",
    },
    {
        arabicName: "دال ماش مقلي",
        engName: "Daal Mash Fry",
        price: "1.0",
        description:
            "A flavorful lentil dish made with split black gram, fried with onions, tomatoes, and spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "89",
    },
    {
        arabicName: "دال مقلي",
        engName: "Daal Fry",
        price: "1.0",
        description:
            "A traditional lentil dish made with yellow lentils, cooked with onions, tomatoes, and spices.",
        category: "CURRY ITEMS",
        image: "",
        productId: "90",
    },

    // DISH OF THE DAY
    {
        arabicName: "باية",
        engName: "Paaya",
        price: "As Per Market Price",
        description:
            "A rich and flavorful dish made with slow-cooked goat or beef trotters, infused with aromatic spices.",
        category: "DISH OF THE DAY",
        image: "",
        productId: "91",
    },
    {
        arabicName: "نهاري",
        engName: "Nehari",
        price: "As Per Market Price",
        description:
            "A spicy and savory stew of slow-cooked beef or lamb shank, known for its deep flavors.",
        category: "DISH OF THE DAY",
        image: "",
        productId: "92",
    },
    {
        arabicName: "حليم",
        engName: "Haleem",
        price: "As Per Market Price",
        description:
            "A wholesome and hearty dish made with a blend of lentils, wheat, and slow-cooked meat, garnished with fried onions and spices.",
        category: "DISH OF THE DAY",
        image: "",
        productId: "93",
    },

    // RICE
    {
        arabicName: "دم بوخت برياني دجاج",
        engName: "Chicken Dum Pukht Biryani",
        price: 4.5,
        description:
            "Aromatic chicken biryani cooked in a traditional Dum Pukht style with layers of spiced rice and tender chicken.",
        category: "RICE",
        image: "",
        productId: "94",
    },
    {
        arabicName: "دم بوخت برياني لحم",
        engName: "Mutton Dum Pukht Biryani",
        price: 6.0,
        description:
            "Flavorful mutton biryani prepared with slow-cooked marinated mutton and fragrant basmati rice.",
        category: "RICE",
        image: "",
        productId: "95",
    },
    {
        arabicName: "برياني دجاج",
        engName: "Chicken Biryani",
        price: 1.2,
        description:
            "Classic chicken biryani with spiced chicken pieces and basmati rice.",
        category: "RICE",
        image: "",
        productId: "96",
    },
    {
        arabicName: "مجبوس دجاج األفغاني",
        engName: "Chicken Afghani Pulao",
        price: 1.2,
        description:
            "Afghani-style pulao with tender chicken and fragrant rice.",
        category: "RICE",
        image: "",
        productId: "97",
    },
    {
        arabicName: "مجبوس بالدجاج",
        engName: "Chicken Pulao",
        price: 1.2,
        description:
            "Delicious chicken pulao made with seasoned rice and chicken.",
        category: "RICE",
        image: "",
        productId: "98",
    },
    {
        arabicName: "غوزي دجاج )كامل",
        engName: "Chicken Ghuzzi (Full)",
        price: 6.0,
        description:
            "A full serving of roasted chicken Ghuzzi served with rice.",
        category: "RICE",
        image: "",
        productId: "99",
    },
    {
        arabicName: "غوزي دجاج )نصف",
        engName: "Chicken Ghuzzi (Half)",
        price: 3.5,
        description: "Half serving of roasted chicken Ghuzzi served with rice.",
        category: "RICE",
        image: "",
        productId: "100",
    },
    {
        arabicName: "مندي دجاج )كامل",
        engName: "Chicken Mandi (Full)",
        price: 5.8,
        description:
            "Traditional Yemeni chicken mandi, full serving, cooked with aromatic rice.",
        category: "RICE",
        image: "",
        productId: "101",
    },
    {
        arabicName: "مندي دجاج )نصف",
        engName: "Chicken Mandi (Half)",
        price: 3.0,
        description: "Half serving of chicken mandi cooked with spiced rice.",
        category: "RICE",
        image: "",
        productId: "102",
    },
    {
        arabicName: "برياني لحم",
        engName: "Mutton Biryani",
        price: 2.0,
        description:
            "Spicy and flavorful mutton biryani with tender mutton pieces and basmati rice.",
        category: "RICE",
        image: "",
        productId: "103",
    },
    {
        arabicName: "مجبوس بالحم",
        engName: "Mutton Pulao",
        price: 2.0,
        description:
            "Aromatic mutton pulao with seasoned rice and tender mutton.",
        category: "RICE",
        image: "",
        productId: "104",
    },
    {
        arabicName: "مندي لحم",
        engName: "Lamb Mandi",
        price: 3.5,
        description:
            "Traditional lamb mandi cooked with spiced rice and tender lamb.",
        category: "RICE",
        image: "",
        productId: "105",
    },
    {
        arabicName: "برياني بالسمك",
        engName: "Fish Biryani",
        price: 2.2,
        description:
            "Delicious fish biryani made with aromatic rice and spiced fish.",
        category: "RICE",
        image: "",
        productId: "106",
    },
    {
        arabicName: "برياني بالروبيان",
        engName: "Prawn Biryani",
        price: 2.2,
        description:
            "Aromatic prawn biryani with seasoned rice and succulent prawns.",
        category: "RICE",
        image: "",
        productId: "107",
    },
    {
        arabicName: "البازالء مجبوس",
        engName: "Peas Pulao",
        price: 1.0,
        description: "Fragrant pulao rice cooked with green peas.",
        category: "RICE",
        image: "",
        productId: "108",
    },
    {
        arabicName: "أرز زعفران",
        engName: "Zafran Rice",
        price: 1.0,
        description: "Saffron-infused rice with a rich aroma and flavor.",
        category: "RICE",
        image: "",
        productId: "109",
    },
    {
        arabicName: "أرز جيرا",
        engName: "Zeera Rice",
        price: 0.7,
        description: "Rice flavored with cumin seeds, offering a nutty taste.",
        category: "RICE",
        image: "",
        productId: "110",
    },
    {
        arabicName: "أرز أبيض",
        engName: "White Rice",
        price: 0.6,
        description:
            "Simple steamed white rice, perfect to pair with any curry or dish.",
        category: "RICE",
        image: "",
        productId: "111",
    },

    // BREAD
    {
        arabicName: "خبز روغني",
        engName: "Roghni Naan",
        price: 0.3,
        description:
            "Traditional soft naan bread topped with sesame seeds and baked to perfection.",
        category: "BREAD",
        image: "",
        productId: "112",
    },
    {
        arabicName: "خبز بالثوم",
        engName: "Garlic Naan",
        price: 0.3,
        description:
            "Naan bread infused with garlic and butter, baked until golden and fragrant.",
        category: "BREAD",
        image: "",
        productId: "113",
    },
    {
        arabicName: "خبز",
        engName: "Plan Roti",
        price: 0.1,
        description: "Simple and soft roti, perfect to accompany any meal.",
        category: "BREAD",
        image: "",
        productId: "114",
    },

    // BURGER & SHAWARMA
    {
        arabicName: "برجر الدجاج",
        engName: "Chicken Burger",
        price: 1.2,
        description:
            "Juicy grilled chicken patty served in a fresh bun with lettuce, tomato, and special sauce.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "115",
    },
    {
        arabicName: "برجر باللحم",
        engName: "Lamb Burger",
        price: 1.5,
        description:
            "Tender lamb patty with a perfect blend of spices, served with lettuce, tomato, and onion in a soft bun.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "116",
    },
    {
        arabicName: "دجاج مغلم بالجبن",
        engName: "Chicken Mughlam with Cheese",
        price: 0.6,
        description:
            "Grilled chicken fillet topped with melted cheese, served in a bun with fresh vegetables.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "117",
    },
    {
        arabicName: "لحم مغلم بالجبن",
        engName: "Lamb Mughlam with Cheese",
        price: 0.6,
        description:
            "Grilled lamb fillet with melted cheese, served in a soft bun with fresh vegetables.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "118",
    },
    {
        arabicName: "كباب مغلم",
        engName: "Kabab Muglam",
        price: 0.8,
        description:
            "Spiced minced meat kabab, grilled to perfection, served in a bun with salad and sauce.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "119",
    },
    {
        arabicName: "كلوب ساندوتش",
        engName: "Club Sandwich",
        price: 1.5,
        description:
            "Triple-decker sandwich with chicken, bacon, lettuce, tomato, and mayonnaise.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "120",
    },
    {
        arabicName: "شيش طاووق ساندوتش",
        engName: "Sheesh Tawouk Sandwich",
        price: 0.8,
        description:
            "Marinated chicken chunks grilled and served in a wrap with garlic sauce and vegetables.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "121",
    },
    {
        arabicName: "ساندوتش دجاج",
        engName: "Chicken Sandwich",
        price: 0.7,
        description:
            "Grilled chicken breast served in a bun with lettuce, tomato, and mayonnaise.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "122",
    },
    {
        arabicName: "ساندوتش بالجبن",
        engName: "Cheese Sandwich",
        price: 0.7,
        description:
            "A simple yet delicious sandwich with melted cheese and fresh vegetables.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "123",
    },
    {
        arabicName: "ميني شاورما - برد",
        engName: "Mini Cold Shawarma",
        price: 0.8,
        description:
            "Small shawarma wrap with cold cuts, perfect for a quick snack.",
        category: "BURGER & SHAWARMA",
        image: "",
        productId: "124",
    },

    // REFRESHMENTS
    {
        arabicName: "عصير برتقال طازج",
        engName: "Fresh Orange Juice",
        price: 1.5,
        description:
            "Freshly squeezed orange juice, rich in vitamin C and natural flavors.",
        category: "REFRESHMENTS",
        image: "",
        productId: "125",
    },
    {
        arabicName: "عصير كوكتيل",
        engName: "Cocktail Juice",
        price: 1.5,
        description:
            "A refreshing blend of various fresh fruit juices, perfect for a hot day.",
        category: "REFRESHMENTS",
        image: "",
        productId: "126",
    },
    {
        arabicName: "حمص",
        engName: "Fresh Lemon & Mint Juice",
        price: 1.2,
        description:
            "A zesty and refreshing drink made from fresh lemons and mint leaves.",
        category: "REFRESHMENTS",
        image: "",
        productId: "127",
    },
    {
        arabicName: "المشروبات",
        engName: "Soft Drinks",
        price: 0.35,
        description:
            "Chilled and fizzy soft drinks available in various flavors.",
        category: "REFRESHMENTS",
        image: "",
        productId: "128",
    },
    {
        arabicName: "مياه معدنية (كبيرة)",
        engName: "Mineral Water (Large)",
        price: 0.3,
        description:
            "Large bottle of pure mineral water, perfect for staying hydrated.",
        category: "REFRESHMENTS",
        image: "",
        productId: "129",
    },
    {
        arabicName: "مياه معدنية (صغيرة)",
        engName: "Mineral Water (Small)",
        price: 0.2,
        description:
            "Small bottle of pure mineral water, convenient for on-the-go hydration.",
        category: "REFRESHMENTS",
        image: "",
        productId: "130",
    },
    {
        arabicName: "قهوة",
        engName: "Coffee",
        price: 0.4,
        description:
            "A warm and aromatic cup of freshly brewed coffee to kickstart your day.",
        category: "REFRESHMENTS",
        image: "",
        productId: "131",
    },
    {
        arabicName: "شاي",
        engName: "Tea",
        price: 0.2,
        description: "A soothing cup of tea, available in different flavors.",
        category: "REFRESHMENTS",
        image: "",
        productId: "132",
    },

    // SWEETS
    {
        arabicName: "أم علي",
        engName: "Um Ali",
        price: 0.8,
        description:
            "A traditional Egyptian dessert made from puff pastry, milk, and nuts, baked to perfection.",
        category: "SWEETS",
        image: "",
        productId: "133",
    },
    {
        arabicName: "غالب جامن (٢ قطعة)",
        engName: "Gulam Jamun (2 pcs.)",
        price: 0.7,
        description:
            "A classic South Asian sweet, consisting of deep-fried milk solids soaked in sugar syrup.",
        category: "SWEETS",
        image: "",
        productId: "134",
    },
    {
        arabicName: "بودنغ باألرز",
        engName: "Rice Pudding",
        price: 0.8,
        description:
            "Creamy and rich rice pudding, flavored with aromatic spices and topped with nuts.",
        category: "SWEETS",
        image: "",
        productId: "135",
    },
    {
        arabicName: "بيت األياود خاصة",
        engName: "Bait Al Ayawed Special",
        price: 1.5,
        description:
            "A special dessert unique to the restaurant, featuring a mix of traditional ingredients.",
        category: "SWEETS",
        image: "",
        productId: "136",
    },
];

module.exports = menuItems;